locale_ids = {'afrikaans - south africa': '0436',
              'afrikaans': '0436',
              'albanian - albania': '041c',
              'alsatian': '0484',
              'amharic - ethiopia': '045e',
              'arabic - algeria': '1401',
              'arabic - bahrain': '3c01',
              'arabic - egypt': '0c01',
              'arabic - iraq': '0801',
              'arabic - jordan': '2c01',
              'arabic - kuwait': '3401',
              'arabic - lebanon': '3001',
              'arabic - libya': '1001',
              'arabic - morocco': '1801',
              'arabic - oman': '2001',
              'arabic - qatar': '4001',
              'arabic - saudi arabia': '0401',
              'arabic': '0401',
              'arabic - syria': '2801',
              'arabic - tunisia': '1c01',
              'arabic - u.a.e.': '3801',
              'arabic - united arabic emirates': '3801',
              'arabic - yemen': '2401',
              'armenian - armenia': '042b',
              'assamese': '044d',
              'azeri (cyrillic)': '082c',
              'azeri (latin)': '042c',
              'bashkir': '046d',
              'basque': '042d',
              'belarusian': '0423',
              'bengali (bangladesh)': '0845',
              'bengali (india)': '0445',
              'bosnian (bosnia/herzegovina)': '141a',
              'breton': '047e',
              'bulgarian': '0402',
              'burmese': '0455',
              'catalan': '0403',
              'cherokee - united states': '045c',
              'chinese - hong kong sar': '0c04',
              'chinese - macao sar': '1404',
              "chinese - people's republic of china": '0804',
              'chinese': '0804',
              'chinese - singapore': '1004',
              'chinese - taiwan': '0404',
              'corsican': '0483',
              'croatian': '041a',
              'croatian (bosnia/herzegovina)': '101a',
              'czech': '0405',
              'danish': '0406',
              'dari': '048c',
              'divehi': '0465',
              'dutch - belgium': '0813',
              'dutch - netherlands': '0413',
              'dutch': '0413',
              'edo': '0466',
              'english - australia': '0c09',
              'english - belize': '2809',
              'english - canada': '1009',
              'english - caribbean': '2409',
              'english - hong kong sar': '3c09',
              'english - india': '4009',
              'english - indonesia': '3809',
              'english - ireland': '1809',
              'english - jamaica': '2009',
              'english - malaysia': '4409',
              'english - new zealand': '1409',
              'english - philippines': '3409',
              'english - singapore': '4809',
              'english - south africa': '1c09',
              'english - trinidad': '2c09',
              'english - united kingdom': '0809',
              'english - united states': '0409',
              'english - us': '0409',
              'english': '0409',
              'english - zimbabwe': '3009',
              'estonian': '0425',
              'fyro macedonian': '042f',
              'faroese': '0438',
              'farsi': '0429',
              'filipino': '0464',
              'finnish': '040b',
              'french - belgium': '080c',
              'french - cameroon': '2c0c',
              'french - canada': '0c0c',
              'french - cote dâ€™ivoire': '300c',
              'french - democratic rep. of congo': '240c',
              'french - france': '040c',
              'french': '040c',
              'french - haiti': '3c0c',
              'french - luxembourg': '140c',
              'french - mali': '340c',
              'french - monaco': '180c',
              'french - morocco': '380c',
              'french - north africa': 'e40c',
              'french - reunion': '200c',
              'french - senegal': '280c',
              'french - switzerland': '100c',
              'french - west indies': '1c0c',
              'frisian - netherlands': '0462',
              'fulfulde - nigeria': '0467',
              'galician': '0456',
              'georgian': '0437',
              'german - austria': '0c07',
              'german - germany': '0407',
              'german': '0407',
              'german - liechtenstein': '1407',
              'german - luxembourg': '1007',
              'german - switzerland': '0807',
              'greek': '0408',
              'greenlandic': '046f',
              'guarani - paraguay': '0474',
              'gujarati': '0447',
              'hid (human interface device)': '04ff',
              'hausa - nigeria': '0468',
              'hawaiian - united states': '0475',
              'hebrew': '040d',
              'hindi': '0439',
              'hungarian': '040e',
              'ibibio - nigeria': '0469',
              'icelandic': '040f',
              'igbo - nigeria': '0470',
              'indonesian': '0421',
              'inuktitut': '045d',
              'irish': '083c',
              'italian - italy': '0410',
              'italian - switzerland': '0810',
              'japanese': '0411',
              'kannada': '044b',
              'kanuri - nigeria': '0471',
              'kashmiri': '0860',
              'kashmiri (arabic)': '0460',
              'kazakh': '043f',
              'khmer': '0453',
              'kinyarwanda': '0487',
              'konkani': '0457',
              'korean': '0412',
              'kyrgyz (cyrillic)': '0440',
              'kâ€™iche': '0486',
              'lao': '0454',
              'latin': '0476',
              'latvian': '0426',
              'lithuanian': '0427',
              'luxembourgish': '046e',
              'malay - brunei darussalam': '083e',
              'malay - malaysia': '043e',
              'malayalam': '044c',
              'maltese': '043a',
              'manipuri': '0458',
              'maori - new zealand': '0481',
              'mapudungun': '0471',
              'marathi': '044e',
              'mohawk': '047c',
              'mongolian (cyrillic)': '0450',
              'mongolian (mongolian)': '0850',
              'nepali': '0461',
              'nepali - india': '0861',
              'norwegian (bokmã¥l)': '0414',
              'norwegian (nynorsk)': '0814',
              'occitan': '0482',
              'oriya': '0448',
              'oromo': '0472',
              'papiamentu': '0479',
              'pashto': '0463',
              'polish': '0415',
              'portuguese - brazil': '0416',
              'portuguese - portugal': '0816',
              'punjabi': '0446',
              'punjabi (pakistan)': '0846',
              'quecha - bolivia': '046b',
              'quecha - ecuador': '086b',
              'quecha - peru': '0c6b',
              'rhaeto-romanic': '0417',
              'romanian': '0418',
              'romanian - moldava': '0818',
              'russian': '0419',
              'russian - moldava': '0819',
              'sami (lappish)': '043b',
              'sanskrit': '044f',
              'scottish gaelic': '043c',
              'sepedi': '046c',
              'serbian (cyrillic)': '0c1a',
              'serbian (latin)': '081a',
              'sindhi - india': '0459',
              'sindhi - pakistan': '0859',
              'sinhalese - sri lanka': '045b',
              'slovak': '041b',
              'slovenian': '0424',
              'somali': '0477',
              'sorbian': '042e',
              'spanish - argentina': '2c0a',
              'spanish - bolivia': '400a',
              'spanish - chile': '340a',
              'spanish - colombia': '240a',
              'spanish - costa rica': '140a',
              'spanish - dominican republic': '1c0a',
              'spanish - ecuador': '300a',
              'spanish - el salvador': '440a',
              'spanish - guatemala': '100a',
              'spanish - honduras': '480a',
              'spanish - latin america': '580a',
              'spanish - mexico': '080a',
              'spanish - nicaragua': '4c0a',
              'spanish - panama': '180a',
              'spanish - paraguay': '3c0a',
              'spanish - peru': '280a',
              'spanish - puerto rico': '500a',
              'spanish - spain (modern sort)': '0c0a',
              'spanish': '0c0a',
              'spanish - spain (traditional sort)': '040a',
              'spanish - united states': '540a',
              'spanish - uruguay': '380a',
              'spanish - venezuela': '200a',
              'sutu': '0430',
              'swahili': '0441',
              'swedish': '041d',
              'swedish - finland': '081d',
              'syriac': '045a',
              'tajik': '0428',
              'tamazight (arabic)': '045f',
              'tamazight (latin)': '085f',
              'tamil': '0449',
              'tatar': '0444',
              'telugu': '044a',
              'thai': '041e',
              'tibetan - bhutan': '0851',
              "tibetan - people's republic of china": '0451',
              'tigrigna - eritrea': '0873',
              'tigrigna - ethiopia': '0473',
              'tsonga': '0431',
              'tswana': '0432',
              'turkish': '041f',
              'turkmen': '0442',
              'uighur - china': '0480',
              'ukrainian': '0422',
              'urdu': '0420',
              'urdu - india': '0820',
              'uzbek (cyrillic)': '0843',
              'uzbek (latin)': '0443',
              'venda': '0433',
              'vietnamese': '042a',
              'welsh': '0452',
              'wolof': '0488',
              'xhosa': '0434',
              'yakut': '0485',
              'yi': '0478',
              'yiddish': '043d',
              'yoruba': '046a',
              'zulu': '0435'}

alphabets = {"latin": "abcdefghijklmnopqrstuvwxyz.,';"}

sc = {'nums': ['02', '03', '04', '05', '06', '07', '08', '09', '0a', '0b'],
      'top_row': ['']
      }

stuff = """# layout (anishtro)
q l u c j k p m w -
a n i s v b h t r o
/ ; y g x z f d . ,
e


# configuration
effort: 4
3.0 2.4 2.0 2.2 3.2 3.2 2.2 2.0 2.4 3.0  4.4 4.4
1.6 1.3 1.1 1.0 2.9 2.9 1.0 1.1 1.3 1.6  3.4
3.2 2.6 2.3 1.6 3.0 3.0 1.6 2.3 2.6 3.2
1.0
penalties:
 2.5  3.0  4.0  #same-finger
 0.5  1.0  1.5  #pinky-ring
 0.1  0.2  0.3  #ring-middle
-0.2 -0.1  0.0  #middle-index
fingers: 4
0 1 2 3 3 6 6 7 8 9 3 6
0 1 2 3 3 6 6 7 8 9 9
0 1 2 3 3 6 6 7 8 9
4
type:
matrix"""
